// Code generated by go-localize; DO NOT EDIT.
// This file was generated by robots at
// 2026-03-04 15:49:15.642691863 +1200 +12 m=+0.000297330

package localizations

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

var localizations = map[string]string{
	"en.messages.clear_filter":         "clear filter",
	"en.messages.close_help":           "close help",
	"en.messages.cursor_down":          "cursor down",
	"en.messages.cursor_up":            "cursor up",
	"en.messages.enter":                "enter",
	"en.messages.err_no_json_provided": "You must provide a JSON file!",
	"en.messages.filter":               "filter",
	"en.messages.go_to_end":            "go to end",
	"en.messages.go_to_start":          "go to start",
	"en.messages.left":                 "left",
	"en.messages.next_page":            "next page",
	"en.messages.overall_rating":       "			OVERALL ALBUM RATING: {{.rating}} / 5.00 ",
	"en.messages.path_to_json":         "Path to the JSON file.",
	"en.messages.prev_page":            "prev page",
	"en.messages.quit":                 "quit",
	"en.messages.rate_down":            "rate down",
	"en.messages.rate_up":              "rate up",
	"en.messages.rating_album_by":      "Rating '{{.title}}' by {{.authors}}",
	"en.messages.right":                "right",
	"en.messages.save_ratings":         "export ratings as JSON",
	"en.messages.saved_ratings":        "Successfully saved ratings!",
	"en.messages.show_help":            "show help",
	"ru.messages.clear_filter":         "очистить фильтр",
	"ru.messages.close_help":           "закрыть",
	"ru.messages.cursor_down":          "курсор вниз",
	"ru.messages.cursor_up":            "курсор вверх",
	"ru.messages.enter":                "enter",
	"ru.messages.err_no_json_provided": "Вы должны указать путь к JSON файлу!",
	"ru.messages.filter":               "фильтр",
	"ru.messages.go_to_end":            "в конец",
	"ru.messages.go_to_start":          "в начало",
	"ru.messages.left":                 "лево",
	"ru.messages.next_page":            "следующая страница",
	"ru.messages.overall_rating":       "			ОБЩАЯ ОЦЕНКА АЛЬБОМА: {{.rating}} / 5.00 ",
	"ru.messages.path_to_json":         "Путь к JSON файлу.",
	"ru.messages.prev_page":            "предыдущая страница",
	"ru.messages.quit":                 "выйти",
	"ru.messages.rate_down":            "понизить оценку",
	"ru.messages.rate_up":              "повысить оценку",
	"ru.messages.rating_album_by":      "Оценка альбома '{{.title}}' от {{.authors}}",
	"ru.messages.right":                "право",
	"ru.messages.save_ratings":         "сохранить оценку",
	"ru.messages.saved_ratings":        "Оценка успешно сохранена!",
	"ru.messages.show_help":            "подробнее",
}

type Replacements map[string]interface{}

type Localizer struct {
	Locale         string
	FallbackLocale string
	Localizations  map[string]string
}

func New(locale string, fallbackLocale string) *Localizer {
	t := &Localizer{Locale: locale, FallbackLocale: fallbackLocale}
	t.Localizations = localizations
	return t
}

func (t Localizer) SetLocales(locale, fallback string) Localizer {
	t.Locale = locale
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) SetLocale(locale string) Localizer {
	t.Locale = locale
	return t
}

func (t Localizer) SetFallbackLocale(fallback string) Localizer {
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) GetWithLocale(locale, key string, replacements ...*Replacements) string {
	str, ok := t.Localizations[t.getLocalizationKey(locale, key)]
	if !ok {
		str, ok = t.Localizations[t.getLocalizationKey(t.FallbackLocale, key)]
		if !ok {
			return key
		}
	}

	// If the str doesn't have any substitutions, no need to
	// template.Execute.
	if strings.Index(str, "}}") == -1 {
		return str
	}

	return t.replace(str, replacements...)
}

func (t Localizer) Get(key string, replacements ...*Replacements) string {
	str := t.GetWithLocale(t.Locale, key, replacements...)
	return str
}

func (t Localizer) getLocalizationKey(locale string, key string) string {
	return fmt.Sprintf("%v.%v", locale, key)
}

func (t Localizer) replace(str string, replacements ...*Replacements) string {
	b := &bytes.Buffer{}
	tmpl, err := template.New("").Parse(str)
	if err != nil {
		return str
	}

	replacementsMerge := Replacements{}
	for _, replacement := range replacements {
		for k, v := range *replacement {
			replacementsMerge[k] = v
		}
	}

	err = template.Must(tmpl, err).Execute(b, replacementsMerge)
	if err != nil {
		return str
	}
	buff := b.String()
	return buff
}
